---

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Debian servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: copy index.php to webserver
    tags: apache,apache,apache2
    copy:
     src: files/
     dest: /var/www/html/
     owner: root
     group: root
     mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariaDB server
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Linux Mint"

